spring.application.name=tp-15-Spring

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/demo_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8086